version: '3.5'
networks:
  nginx-proxy:
    external: true
services:
  go-qrserve:
    container_name: go-qrserve
    restart: always
    image: silentk/qrserve
    networks:
      - nginx-proxy
    environment:
      - VIRTUAL_HOST=qr.ludovic-frank.fr
